repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.4
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: pyrefly-check
        name: Pyrefly (type checking)
        entry: pyrefly check
        language: system
        pass_filenames: false
