---  
name: 🚀 Feature Request  
description: Suggest an idea for this project  
title: "[FEAT] "  
labels: ["enhancement"]  
assignees: []  
body:  
  - type: markdown  
    attributes:  
      value: |  
        Thanks for suggesting a new feature!  
  
  - type: checkboxes  
    id: repository-check  
    attributes:  
      label: Repository Check  
      description: Please verify you're in the right repository  
      options:  
        - label: I have verified this is the correct repository for this feature  
          required: true  
        - label: This is NOT about HTTP signatures (should be in `apsig` repo)  
          required: true  
        - label: This is NOT about ActivityStreams models (should be in `apmodel` repo)  
          required: true  
  
  - type: textarea  
    id: feature-description  
    attributes:  
      label: Feature Description  
      description: A clear and concise description of the feature you'd like to see added  
      placeholder: Describe the feature...  
    validations:  
      required: true  
  
  - type: textarea  
    id: motivation  
    attributes:  
      label: Motivation  
      description: Please explain why this feature would be useful and what problem it solves  
      placeholder: Why is this feature needed?  
    validations:  
      required: true  
  
  - type: textarea  
    id: proposed-solution  
    attributes:  
      label: Proposed Solution  
      description: A clear description of what you want to happen  
      placeholder: How should this feature work?  
    validations:  
      required: true  
  
  - type: textarea  
    id: alternatives  
    attributes:  
      label: Alternatives Considered  
      description: Please describe alternative solutions or features you've considered  
      placeholder: What other approaches have you considered?  
  
  - type: textarea  
    id: additional-context  
    attributes:  
      label: Additional Context  
      description: Add any other context, mockups, or examples about the feature request here  
      placeholder: Any additional information...
---
